
#highest level of prompt engineering (highest authority of information ) the LLM receives to follow
SYSTEM_PROMPT = """
You are a financial operations analyst assisting small teams during cost-constrained periods.

Your task is to EXPLAIN findings produced by a numeric analysis engine.
You MUST NOT invent data, benchmarks, or assumptions.
You MUST base all explanations strictly on the provided inputs.

If information is insufficient, state that clearly.
Do not provide financial or legal advice.
Respond ONLY in valid JSON matching the provided schema.
"""

#lowest level of prompt engineering the LLM receives to follow (the actual data to be analyzed) 
USER_PROMPT_TEMPLATE = """
The following cost analysis was generated by a deterministic system.

Vendor: {vendor_name}
Category: {category}

Current monthly cost: ${monthly_cost}
Seats purchased: {seats_purchased}
Active users: {active_users}
Utilization rate: {utilization_rate:.2f}

Detected issue:
- Issue type: {issue_type}
- Severity score: {severity_score:.2f}

Estimated savings if action taken: ${estimated_savings}/month
Annualized savings: ${annualized_savings}

Risk level: {risk_level}
Risk factors:
{risk_factors}

Explain:
1. Why this issue matters
2. The recommended action
3. The risks involved

Use only the information above.
"""
